// Single source of truth for personal data used across pages.
// Localized copy lives in i18n/translations.ts; only non-translatable data lives here.

import { SITE_URL } from './site';

export const BASE_URL = SITE_URL;

export const profile = {
  name: 'Gonzalo Daniel Vega',
  // 4:3 saliency crop of foto.png, generated by scripts/optimize-foto.mjs
  avatarUrl: '/foto-badge.webp',
  isOpenToWork: true,
  linkedin: 'https://www.linkedin.com/in/gonzalo-daniel-vega/',
  // GITHUB: la URL queda declarada aunque los links esten comentados, para que al
  // reactivar el footer no quede un undefined en silencio.
  github: 'https://github.com/DanielVega1221',
  email: 'dvega6442@gmail.com',
  whatsapp: '5493834368748',
  cv: {
    es: '/cv-es.pdf',
    en: '/cv-en.pdf',
  },
} as const;

/** Absolute URL for the resume: a QR code needs one to be scannable from a phone. */
export function absoluteCvUrl(lang: 'es' | 'en'): string {
  return `${BASE_URL}${lang === 'es' ? profile.cv.es : profile.cv.en}`;
}

/**
 * Absolute URL that makes the server send the file as an attachment instead of
 * opening it in a tab. Vercel route rules can't match a query string (the old
 * `?dl=1` header never worked and broke the deploy config), so this goes
 * through the /api/cv serverless function instead. The plain URL still
 * previews inline, which is what the header and footer want.
 */
export function absoluteCvDownloadUrl(lang: 'es' | 'en'): string {
  return `${BASE_URL}/api/cv?lang=${lang}`;
}
